#!/bin/bash

#--- есть физический диск /dev/sda, только что подключили к машине
#--- в нем разделы /dev/sda1  /dev/sda2  /dev/sda3  /devsda4
#--- надо примаунтить к системе раздел /sda3 с названием  work
#--- создаем в /mnt папку work
#--- и маунтим диск в систему

$ cd /mnt
$ sudo mkdir work
$ sudo mount -v /dev/sda3 /mnt/work

#--- теперь можно с разделом работать
